name: Twenty Sequential Jobs

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 1"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 2"

  job-3:
    runs-on: ubuntu-latest
    needs: job-2
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 3"

  job-4:
    runs-on: ubuntu-latest
    needs: job-3
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 4"

  job-5:
    runs-on: ubuntu-latest
    needs: job-4
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 5"

  job-6:
    runs-on: ubuntu-latest
    needs: job-5
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 6"

  job-7:
    runs-on: ubuntu-latest
    needs: job-6
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 7"

  job-8:
    runs-on: ubuntu-latest
    needs: job-7
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 8"

  job-9:
    runs-on: ubuntu-latest
    needs: job-8
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 9"

  job-10:
    runs-on: ubuntu-latest
    needs: job-9
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 10"

  job-11:
    runs-on: ubuntu-latest
    needs: job-10
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 11"

  job-12:
    runs-on: ubuntu-latest
    needs: job-11
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 12"

  job-13:
    runs-on: ubuntu-latest
    needs: job-12
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 13"

  job-14:
    runs-on: ubuntu-latest
    needs: job-13
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 14"

  job-15:
    runs-on: ubuntu-latest
    needs: job-14
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 15"

  job-16:
    runs-on: ubuntu-latest
    needs: job-15
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 16"

  job-17:
    runs-on: ubuntu-latest
    needs: job-16
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 17"

  job-18:
    runs-on: ubuntu-latest
    needs: job-17
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 18"

  job-19:
    runs-on: ubuntu-latest
    needs: job-18
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 19"

  job-20:
    runs-on: ubuntu-latest
    needs: job-19
    steps:
      - name: Print Hello
        run: echo "Hello World from Job 20"
